APP_TARGET = 'QuickFirebaseDemo'
PROJECT_PATH = '../node_modules/'
platform :ios, '9.0'

target 'QuickFirebaseDemo' do
  pod 'React', :path => PROJECT_PATH + 'react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTLinkingIOS',
    'RCTImage',
    'RCTAnimation',
    'RCTWebSocket', # needed for debugging
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTSettings',
    'RCTVibration',
    'BatchedBridge',
    'DevSupport'
    ]
  pod 'Yoga', :path => PROJECT_PATH + 'react-native/ReactCommon/yoga'
  pod 'RNQuickFirebase', :path => PROJECT_PATH + 'react-native-quick-firebase/ios'
  pod 'Firebase/Auth'
  pod 'FirebaseAnalytics'
end
